package com.cxy.dao;

import com.cxy.entity.CommonImage;

public interface CommonImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    int insert(CommonImage commonImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    int insertSelective(CommonImage commonImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    CommonImage selectByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommonImage commonImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommonImage commonImage);
}