package com.cxy.dao;


import com.cxy.entity.Subscribe;

import java.util.List;

public interface SubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    int insert(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    int insertSelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    Subscribe selectByPrimaryKey(Long subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subscribe record);

    List<Subscribe> selectByLineinfoId(Integer lineinfoId);
}