package com.cxy.entity;

import java.io.Serializable;
import java.util.Date;

public class Identity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.identity_id
     *
     * @mbggenerated
     */
    private Integer identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.positive
     *
     * @mbggenerated
     */
    private String positive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.negative
     *
     * @mbggenerated
     */
    private String negative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.id_card_number
     *
     * @mbggenerated
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table identity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.identity_id
     *
     * @return the value of identity.identity_id
     *
     * @mbggenerated
     */
    public Integer getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.identity_id
     *
     * @param identityId the value for identity.identity_id
     *
     * @mbggenerated
     */
    public void setIdentityId(Integer identityId) {
        this.identityId = identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.user_id
     *
     * @return the value of identity.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.user_id
     *
     * @param userId the value for identity.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.positive
     *
     * @return the value of identity.positive
     *
     * @mbggenerated
     */
    public String getPositive() {
        return positive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.positive
     *
     * @param positive the value for identity.positive
     *
     * @mbggenerated
     */
    public void setPositive(String positive) {
        this.positive = positive == null ? null : positive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.negative
     *
     * @return the value of identity.negative
     *
     * @mbggenerated
     */
    public String getNegative() {
        return negative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.negative
     *
     * @param negative the value for identity.negative
     *
     * @mbggenerated
     */
    public void setNegative(String negative) {
        this.negative = negative == null ? null : negative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.real_name
     *
     * @return the value of identity.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.real_name
     *
     * @param realName the value for identity.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.id_card_number
     *
     * @return the value of identity.id_card_number
     *
     * @mbggenerated
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.id_card_number
     *
     * @param idCardNumber the value for identity.id_card_number
     *
     * @mbggenerated
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity.create_time
     *
     * @return the value of identity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity.create_time
     *
     * @param createTime the value for identity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", identityId=").append(identityId);
        sb.append(", userId=").append(userId);
        sb.append(", positive=").append(positive);
        sb.append(", negative=").append(negative);
        sb.append(", realName=").append(realName);
        sb.append(", idCardNumber=").append(idCardNumber);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}