package com.cxy.entity;

import java.io.Serializable;
import java.util.Date;

public class LineInfo implements Serializable {



    public Integer getBegin() {
        return begin;
    }

    public void setBegin(Integer begin) {
        this.begin = begin;
    }

    private Integer begin;

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    private Integer pageSize;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.lid
     *
     * @mbggenerated
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.start
     *
     * @mbggenerated
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.end
     *
     * @mbggenerated
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.isBargin
     *
     * @mbggenerated
     */
    private Integer isbargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.person_count
     *
     * @mbggenerated
     */
    private Integer personCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.start_adcode
     *
     * @mbggenerated
     */
    private String startAdcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.start_longitude
     *
     * @mbggenerated
     */
    private Double startLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.start_latitude
     *
     * @mbggenerated
     */
    private Double startLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.end_adcode
     *
     * @mbggenerated
     */
    private String endAdcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.end_longitude
     *
     * @mbggenerated
     */
    private Double endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.end_latitude
     *
     * @mbggenerated
     */
    private Double endLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.user_nickname
     *
     * @mbggenerated
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_info.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table line_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.lid
     *
     * @return the value of line_info.lid
     *
     * @mbggenerated
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.lid
     *
     * @param lid the value for line_info.lid
     *
     * @mbggenerated
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.start
     *
     * @return the value of line_info.start
     *
     * @mbggenerated
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.start
     *
     * @param start the value for line_info.start
     *
     * @mbggenerated
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.end
     *
     * @return the value of line_info.end
     *
     * @mbggenerated
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.end
     *
     * @param end the value for line_info.end
     *
     * @mbggenerated
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.start_time
     *
     * @return the value of line_info.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.start_time
     *
     * @param startTime the value for line_info.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.plate_number
     *
     * @return the value of line_info.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.plate_number
     *
     * @param plateNumber the value for line_info.plate_number
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.price
     *
     * @return the value of line_info.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.price
     *
     * @param price the value for line_info.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.isBargin
     *
     * @return the value of line_info.isBargin
     *
     * @mbggenerated
     */
    public Integer getIsbargin() {
        return isbargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.isBargin
     *
     * @param isbargin the value for line_info.isBargin
     *
     * @mbggenerated
     */
    public void setIsbargin(Integer isbargin) {
        this.isbargin = isbargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.status
     *
     * @return the value of line_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.status
     *
     * @param status the value for line_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.person_count
     *
     * @return the value of line_info.person_count
     *
     * @mbggenerated
     */
    public Integer getPersonCount() {
        return personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.person_count
     *
     * @param personCount the value for line_info.person_count
     *
     * @mbggenerated
     */
    public void setPersonCount(Integer personCount) {
        this.personCount = personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.type
     *
     * @return the value of line_info.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.type
     *
     * @param type the value for line_info.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.user_id
     *
     * @return the value of line_info.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.user_id
     *
     * @param userId the value for line_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.start_adcode
     *
     * @return the value of line_info.start_adcode
     *
     * @mbggenerated
     */
    public String getStartAdcode() {
        return startAdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.start_adcode
     *
     * @param startAdcode the value for line_info.start_adcode
     *
     * @mbggenerated
     */
    public void setStartAdcode(String startAdcode) {
        this.startAdcode = startAdcode == null ? null : startAdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.start_longitude
     *
     * @return the value of line_info.start_longitude
     *
     * @mbggenerated
     */
    public Double getStartLongitude() {
        return startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.start_longitude
     *
     * @param startLongitude the value for line_info.start_longitude
     *
     * @mbggenerated
     */
    public void setStartLongitude(Double startLongitude) {
        this.startLongitude = startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.start_latitude
     *
     * @return the value of line_info.start_latitude
     *
     * @mbggenerated
     */
    public Double getStartLatitude() {
        return startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.start_latitude
     *
     * @param startLatitude the value for line_info.start_latitude
     *
     * @mbggenerated
     */
    public void setStartLatitude(Double startLatitude) {
        this.startLatitude = startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.end_adcode
     *
     * @return the value of line_info.end_adcode
     *
     * @mbggenerated
     */
    public String getEndAdcode() {
        return endAdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.end_adcode
     *
     * @param endAdcode the value for line_info.end_adcode
     *
     * @mbggenerated
     */
    public void setEndAdcode(String endAdcode) {
        this.endAdcode = endAdcode == null ? null : endAdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.end_longitude
     *
     * @return the value of line_info.end_longitude
     *
     * @mbggenerated
     */
    public Double getEndLongitude() {
        return endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.end_longitude
     *
     * @param endLongitude the value for line_info.end_longitude
     *
     * @mbggenerated
     */
    public void setEndLongitude(Double endLongitude) {
        this.endLongitude = endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.end_latitude
     *
     * @return the value of line_info.end_latitude
     *
     * @mbggenerated
     */
    public Double getEndLatitude() {
        return endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.end_latitude
     *
     * @param endLatitude the value for line_info.end_latitude
     *
     * @mbggenerated
     */
    public void setEndLatitude(Double endLatitude) {
        this.endLatitude = endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.user_nickname
     *
     * @return the value of line_info.user_nickname
     *
     * @mbggenerated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.user_nickname
     *
     * @param userNickname the value for line_info.user_nickname
     *
     * @mbggenerated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_info.user_mobile
     *
     * @return the value of line_info.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_info.user_mobile
     *
     * @param userMobile the value for line_info.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", start=").append(start);
        sb.append(", end=").append(end);
        sb.append(", startTime=").append(startTime);
        sb.append(", plateNumber=").append(plateNumber);
        sb.append(", price=").append(price);
        sb.append(", isbargin=").append(isbargin);
        sb.append(", status=").append(status);
        sb.append(", personCount=").append(personCount);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", startAdcode=").append(startAdcode);
        sb.append(", startLongitude=").append(startLongitude);
        sb.append(", startLatitude=").append(startLatitude);
        sb.append(", endAdcode=").append(endAdcode);
        sb.append(", endLongitude=").append(endLongitude);
        sb.append(", endLatitude=").append(endLatitude);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", userMobile=").append(userMobile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}