package com.cxy.entity;

import java.io.Serializable;
import java.util.Date;

public class Subscribe implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.subscribe_id
     *
     * @mbggenerated
     */
    private Long subscribeId;


    public Long getPersonId() {
        return personId;
    }

    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.person_count
     *
     * @mbggenerated
     */
    private Integer personCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.person_mobile
     *
     * @mbggenerated
     */
    private String personMobile;

    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    private String personName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.lineinfo_id
     *
     * @mbggenerated
     */
    private Integer lineinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.subscribe_id
     *
     * @return the value of subscribe.subscribe_id
     *
     * @mbggenerated
     */
    public Long getSubscribeId() {
        return subscribeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.subscribe_id
     *
     * @param subscribeId the value for subscribe.subscribe_id
     *
     * @mbggenerated
     */
    public void setSubscribeId(Long subscribeId) {
        this.subscribeId = subscribeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.person_count
     *
     * @return the value of subscribe.person_count
     *
     * @mbggenerated
     */
    public Integer getPersonCount() {
        return personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.person_count
     *
     * @param personCount the value for subscribe.person_count
     *
     * @mbggenerated
     */
    public void setPersonCount(Integer personCount) {
        this.personCount = personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.person_mobile
     *
     * @return the value of subscribe.person_mobile
     *
     * @mbggenerated
     */
    public String getPersonMobile() {
        return personMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.person_mobile
     *
     * @param personMobile the value for subscribe.person_mobile
     *
     * @mbggenerated
     */
    public void setPersonMobile(String personMobile) {
        this.personMobile = personMobile == null ? null : personMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.description
     *
     * @return the value of subscribe.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.description
     *
     * @param description the value for subscribe.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.create_time
     *
     * @return the value of subscribe.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.create_time
     *
     * @param createTime the value for subscribe.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.lineinfo_id
     *
     * @return the value of subscribe.lineinfo_id
     *
     * @mbggenerated
     */
    public Integer getLineinfoId() {
        return lineinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.lineinfo_id
     *
     * @param lineinfoId the value for subscribe.lineinfo_id
     *
     * @mbggenerated
     */
    public void setLineinfoId(Integer lineinfoId) {
        this.lineinfoId = lineinfoId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subscribeId=").append(subscribeId);
        sb.append(", personCount=").append(personCount);
        sb.append(", personMobile=").append(personMobile);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", lineinfoId=").append(lineinfoId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}